name: first_workflow
on: push
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Running the single command in first job
        run: echo "Hi, Hello, Good morning"
        
