name: first_workflow
on: 
  schedule:
    - cron: "5 * * * *"
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Running the single command in first job
        run: echo "Hi, Hello, Good morning"
      - name: Checking hostname
        run: hostname
  job2:
   name: Second job
   runs-on: ubuntu-latest
   steps:
     - name: Running multiple commands
       run: echo "Good evening all"
            echo "This is is my first day of practise"
  job3:
    name: Third Job
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Hostname
        run: hostname
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: checking hostname
        run: hostname
        
        
